# Generated by Django 5.1.6 on 2025-02-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
