# Generated by Django 5.1.6 on 2025-02-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_notas/'),
        ),
        migrations.AddField(
            model_name='nota',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_notas/'),
        ),
    ]
